webservice:
  container_name: webservice
  build: .
  volumes:
    - .:/usr/src/app/:ro
  ports:
    - "8080:8080"
  command: npm run dev:local:docker
  environment:
    PG_DB_URL: postgres://postgres:password@postgres:5432/results
    BUNYAN_LEVEL: debug
  links:
    - local-postgres:postgres
local-postgres:
  container_name: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: results
  volumes:
    - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro
  expose:
    - "5432"
  ports:
    - "54321:5432"
  image: postgres:9.4
